FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production=false

# Copy source
COPY . .

# Build
RUN npm run build

# Install serve globally
RUN npm install -g serve

# Start
CMD ["serve", "-s", "dist", "-l", "8080"]

EXPOSE 8080